name: WindZ DP

on:
  workflow_dispatch:

jobs:
  build:
    name: Built Connection
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/jahidrdpschool/pc-github-anydesk/main/DL.bat -OutFile DL.bat
          cmd /c DL.bat

      - name: Log In To AnyDesk
        run: cmd /c ST.bat

      - name: Time Counter
        run: Start-Sleep -Seconds 21600
